# Generated by Django 4.1.1 on 2022-10-19 04:34

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppGlobal', '0007_alter_blog_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='slug',
            field=autoslug.fields.AutoSlugField(always_update=True, editable=True, populate_from='titulo'),
        ),
        migrations.DeleteModel(
            name='Autores',
        ),
    ]
